[package]
name = "hexagon"
version = "0.1.0"
authors = ["Lukas Boehm <suluke93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glutin = "0.24"
nalgebra-glm = "0.7.0"
rusttype = "0.8.3"